[package]
name = "kzg-ceremony-test-vectors"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
serde_json = "1.0.91"
kzg-ceremony-crypto = { git = "https://github.com/ethereum/kzg-ceremony-sequencer", rev = "34b5fc8", features = ["arkworks"] }
